import circt.stage.ChiselStage
import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path, Paths}
import npc.rocketmed.RocketChip

object GenerateTop extends App {
  require(args.length == 1, "usage: GenerateTop <output.sv>")
  val output = Paths.get(args(0)).toAbsolutePath.normalize
  val parent = output.getParent
  if (parent != null) Files.createDirectories(parent)

  val firtoolOptions = Array(
    "--lowering-options=" + List(
      "disallowLocalVariables",
      "disallowPackedArrays",
      "locationInfoStyle=wrapInAtSquareBracket"
    ).mkString(",")
  )
  val generated      = ChiselStage.emitSystemVerilog(new RocketChip, Array.empty, firtoolOptions)
  // FIRRTL deduplicates the identical I$ and D$ tag wrappers into ICacheTagSram.
  val sramModules    = Seq("ICacheTagSram", "ICacheDataSram", "DCacheDataSram")
  val synthesisReady = sramModules.foldLeft(generated) { (rtl, moduleName) =>
    val declaration = s"module $moduleName("
    require(rtl.contains(declaration), s"generated RTL is missing SRAM module $moduleName")
    rtl.replace(
      declaration,
      s"`ifdef SYNTHESIS\n(* blackbox *)\n`endif\n$declaration"
    )
  }

  val gprWires  = (0 until 32).map(i => s"  wire [31:0] io_commit_gpr_$i;").mkString("\n")
  val gprCopies = (0 until 32).map(i => s"      event_gpr[$i] = io_commit_gpr_$i;").mkString("\n")

  val wrapper = s"""
// Parameterized external-contract shell generated by GenerateTop.scala.
module ysyx_26030082 #(
  parameter [31:0] RESET_PC = 32'h3000_0000
) (
  input clock,
  input reset,
  input io_interrupt,
  input io_master_awready,
  output io_master_awvalid,
  output [3:0] io_master_awid,
  output [31:0] io_master_awaddr,
  output [7:0] io_master_awlen,
  output [2:0] io_master_awsize,
  output [1:0] io_master_awburst,
  input io_master_wready,
  output io_master_wvalid,
  output [31:0] io_master_wdata,
  output [3:0] io_master_wstrb,
  output io_master_wlast,
  output io_master_bready,
  input io_master_bvalid,
  input [3:0] io_master_bid,
  input [1:0] io_master_bresp,
  input io_master_arready,
  output io_master_arvalid,
  output [3:0] io_master_arid,
  output [31:0] io_master_araddr,
  output [7:0] io_master_arlen,
  output [2:0] io_master_arsize,
  output [1:0] io_master_arburst,
  output io_master_rready,
  input io_master_rvalid,
  input [3:0] io_master_rid,
  input [31:0] io_master_rdata,
  input [1:0] io_master_rresp,
  input io_master_rlast,
  output io_slave_awready,
  input io_slave_awvalid,
  input [3:0] io_slave_awid,
  input [31:0] io_slave_awaddr,
  input [7:0] io_slave_awlen,
  input [2:0] io_slave_awsize,
  input [1:0] io_slave_awburst,
  output io_slave_wready,
  input io_slave_wvalid,
  input [31:0] io_slave_wdata,
  input [3:0] io_slave_wstrb,
  input io_slave_wlast,
  input io_slave_bready,
  output io_slave_bvalid,
  output [3:0] io_slave_bid,
  output [1:0] io_slave_bresp,
  output io_slave_arready,
  input io_slave_arvalid,
  input [3:0] io_slave_arid,
  input [31:0] io_slave_araddr,
  input [7:0] io_slave_arlen,
  input [2:0] io_slave_arsize,
  input [1:0] io_slave_arburst,
  input io_slave_rready,
  output io_slave_rvalid,
  output [3:0] io_slave_rid,
  output [31:0] io_slave_rdata,
  output [1:0] io_slave_rresp,
  output io_slave_rlast
);
  wire [31:0] io_resetVector = RESET_PC;
  wire io_commit_valid;
  wire [31:0] io_commit_pc;
  wire [31:0] io_commit_instruction;
  wire [2:0] io_commit_instructionLength;
  wire io_commit_instructionValid;
  wire [31:0] io_commit_nextPc;
$gprWires
  wire [1:0] io_commit_csr_priv;
  wire [31:0] io_commit_csr_mstatus;
  wire [31:0] io_commit_csr_mtvec;
  wire [31:0] io_commit_csr_mepc;
  wire [31:0] io_commit_csr_mcause;
  wire [31:0] io_commit_csr_mtval;
  wire [31:0] io_commit_csr_medeleg;
  wire [31:0] io_commit_csr_mideleg;
  wire [31:0] io_commit_csr_mie;
  wire [31:0] io_commit_csr_stvec;
  wire [31:0] io_commit_csr_sepc;
  wire [31:0] io_commit_csr_scause;
  wire [31:0] io_commit_csr_stval;
  wire [31:0] io_commit_csr_sscratch;
  wire [31:0] io_commit_csr_satp;
  wire [31:0] io_commit_csr_mscratch;
  wire [31:0] io_commit_csr_menvcfgh;
  wire [31:0] io_commit_csr_mcounteren;
  wire [31:0] io_commit_csr_scounteren;
  wire [31:0] io_commit_csr_mcountinhibit;
  wire [63:0] io_commit_csr_mcycle;
  wire [63:0] io_commit_csr_minstret;
  wire io_asyncInterrupt_valid;
  wire [31:0] io_asyncInterrupt_bits_cause;
  wire [31:0] io_asyncInterrupt_bits_epc;
  wire [31:0] io_asyncInterrupt_bits_target;
  wire io_halted;

  ysyx_26030082_chisel implementation (.*);

`ifdef NPC_SIMULATION
`ifndef SYNTHESIS
`ifndef __ICARUS__
  import "DPI-C" function void npc_arch_event(
    input int unsigned event_type,
    input int unsigned instruction_pc,
    input int unsigned instruction_bits,
    input int unsigned instruction_length,
    input int unsigned instruction_valid,
    input int unsigned cause,
    input int unsigned pretrap_pc,
    input int unsigned post_pc,
    input int unsigned priv,
    input int unsigned mstatus,
    input int unsigned mtvec,
    input int unsigned mepc,
    input int unsigned mcause,
    input int unsigned mtval,
    input int unsigned medeleg,
    input int unsigned mideleg,
    input int unsigned mie,
    input int unsigned stvec,
    input int unsigned sepc,
    input int unsigned scause,
    input int unsigned stval,
    input int unsigned sscratch,
    input int unsigned satp,
    input int unsigned mscratch,
    input int unsigned menvcfgh,
    input int unsigned mcounteren,
    input int unsigned scounteren,
    input int unsigned mcountinhibit,
    input int unsigned gpr[32]
  );
  import "DPI-C" function void npc_axi_sample(
    input int unsigned aw_valid,
    input int unsigned aw_ready,
    input int unsigned aw_addr,
    input int unsigned aw_len,
    input int unsigned w_valid,
    input int unsigned w_ready,
    input int unsigned w_data,
    input int unsigned w_last,
    input int unsigned b_valid,
    input int unsigned b_ready,
    input int unsigned b_id,
    input int unsigned b_resp
  );

  int unsigned event_gpr[32];
  always_comb begin
$gprCopies
  end

  always @(posedge clock) begin
    if (!reset) begin
      npc_axi_sample(io_master_awvalid, io_master_awready,
        io_master_awaddr, io_master_awlen, io_master_wvalid,
        io_master_wready, io_master_wdata, io_master_wlast,
        io_master_bvalid, io_master_bready, io_master_bid,
        io_master_bresp);
      if (io_commit_valid) begin
        npc_arch_event(0, io_commit_pc, io_commit_instruction,
          io_commit_instructionLength, io_commit_instructionValid, 0, 0,
          io_commit_nextPc, io_commit_csr_priv, io_commit_csr_mstatus,
          io_commit_csr_mtvec, io_commit_csr_mepc, io_commit_csr_mcause,
          io_commit_csr_mtval, io_commit_csr_medeleg, io_commit_csr_mideleg,
          io_commit_csr_mie, io_commit_csr_stvec, io_commit_csr_sepc,
          io_commit_csr_scause, io_commit_csr_stval, io_commit_csr_sscratch,
          io_commit_csr_satp, io_commit_csr_mscratch,
          io_commit_csr_menvcfgh, io_commit_csr_mcounteren,
          io_commit_csr_scounteren, io_commit_csr_mcountinhibit, event_gpr);
      end
      if (io_asyncInterrupt_valid) begin
        npc_arch_event(1, 0, 0, 0, 0, io_asyncInterrupt_bits_cause,
          io_asyncInterrupt_bits_epc, io_asyncInterrupt_bits_target,
          io_commit_csr_priv, io_commit_csr_mstatus, io_commit_csr_mtvec,
          io_commit_csr_mepc, io_commit_csr_mcause, io_commit_csr_mtval,
          io_commit_csr_medeleg, io_commit_csr_mideleg, io_commit_csr_mie,
          io_commit_csr_stvec, io_commit_csr_sepc, io_commit_csr_scause,
          io_commit_csr_stval, io_commit_csr_sscratch, io_commit_csr_satp,
          io_commit_csr_mscratch, io_commit_csr_menvcfgh,
          io_commit_csr_mcounteren, io_commit_csr_scounteren,
          io_commit_csr_mcountinhibit, event_gpr);
      end
    end
  end
`endif
`endif
`endif
endmodule
"""

  val provenance =
    "// Generated by npc/src/GenerateTop.scala; do not edit.\n" +
      "// Rocket source revision: 55bcad0f59436de98ea510334121de8546b9e9d7\n"
  Files.writeString(output, provenance + synthesisReady + wrapper, StandardCharsets.UTF_8)
}
