CONTRACT_ID = core/mainargs
CONTRACT_GROUP = core
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_ROOT = ../..
CFLAGS += -DEXPECT_MAINARGS=\"$(mainargs)\"
include $(CONTRACT_ROOT)/contract.mk
